"""
Notifier Integration
Email: SMTP (real) or mock logs
Communicator: Slack webhooks (Slack format) + Discord webhooks (native embeds)
"""
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import httpx

logger = logging.getLogger("sre-agent.notifier")

PRIORITY_EMOJI = {"P1": "🔴", "P2": "🟠", "P3": "🟡", "P4": "🟢"}

# Discord sidebar colors per priority (decimal int)
DISCORD_COLORS = {
    "P1": 0xF85149,  # red
    "P2": 0xFB8500,  # orange
    "P3": 0xE3B341,  # yellow
    "P4": 0x3FB950,  # green
}


class NotifierClient:
    def __init__(self, obs_logger):
        self.obs_logger = obs_logger
        self.mock_email = os.getenv("MOCK_EMAIL", "true").lower() == "true"
        self.smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.smtp_user = os.getenv("SMTP_USER", "")
        self.smtp_pass = os.getenv("SMTP_PASS", "")
        self.from_email = os.getenv("FROM_EMAIL", "sre-agent@yourcompany.com")
        self.team_emails = [
            e.strip()
            for e in os.getenv("TEAM_EMAILS", "oncall@yourcompany.com").split(",")
        ]
        self.slack_webhook = os.getenv("SLACK_WEBHOOK_URL", "")
        self.discord_webhook = os.getenv("DISCORD_WEBHOOK_URL", "")

        if self.mock_email:
            logger.info("Notifier: Email in MOCK mode (logs only)")
        else:
            logger.info(f"Notifier: SMTP {self.smtp_host}:{self.smtp_port}")

        if self.discord_webhook:
            logger.info("Notifier: Discord webhook configured ✅")
        if self.slack_webhook:
            logger.info("Notifier: Slack webhook configured ✅")

    # ── Team Notification ─────────────────────────────────────────────────────
    async def notify_team(self, ticket, triage_result) -> None:
        priority = triage_result.priority
        emoji = PRIORITY_EMOJI.get(priority, "⚠️")
        subject = f"{emoji} [{priority}] New Incident: {ticket.ticket_id}"

        actions_html = "".join(f"<li>{a}</li>" for a in triage_result.recommended_actions)
        services = ", ".join(triage_result.affected_services) or "Unknown"

        # ── Email ─────────────────────────────────────────────────────────────
        html_body = f"""
<html><body style="font-family: monospace; background: #0f0f0f; color: #e0e0e0; padding: 20px;">
<div style="max-width:600px; border: 1px solid #333; border-radius: 8px; overflow: hidden;">
  <div style="background: {'#7c1c1c' if priority in ('P1','P2') else '#1c3a1c'}; padding: 16px 24px;">
    <h2 style="margin:0; color: #fff;">{emoji} {priority} Incident – {ticket.ticket_id}</h2>
  </div>
  <div style="padding: 24px;">
    <p><strong>Summary:</strong><br>{triage_result.summary}</p>
    <p><strong>Root Cause Hypothesis:</strong><br>{triage_result.root_cause_hypothesis}</p>
    <p><strong>Affected Services:</strong> {services}</p>
    <p><strong>Blast Radius:</strong> {triage_result.estimated_blast_radius or 'Under assessment'}</p>
    <p><strong>Recommended Actions:</strong></p>
    <ul>{actions_html}</ul>
    <p><a href="{ticket.url}" style="color: #6cf; text-decoration:none; border: 1px solid #6cf; padding: 8px 16px; border-radius: 4px;">📋 View Ticket →</a></p>
  </div>
  <div style="padding: 12px 24px; background: #1a1a1a; color: #888; font-size: 12px;">
    Auto-generated by SRE Agent • {ticket.provider.upper()} ticketing
  </div>
</div>
</body></html>
"""
        for email in self.team_emails:
            await self._send_email(email, subject, html_body)

        # ── Slack ─────────────────────────────────────────────────────────────
        if self.slack_webhook:
            slack_msg = {
                "text": f"{emoji} *{priority} Incident – {ticket.ticket_id}*",
                "attachments": [{
                    "color": "#e74c3c" if priority in ("P1", "P2") else "#f39c12",
                    "fields": [
                        {"title": "Summary",          "value": triage_result.summary[:500], "short": False},
                        {"title": "Root Cause",       "value": triage_result.root_cause_hypothesis, "short": False},
                        {"title": "Affected Services","value": services, "short": True},
                        {"title": "Confidence",       "value": triage_result.confidence, "short": True},
                    ],
                    "footer": f"SRE Agent | <{ticket.url}|View Ticket>",
                }]
            }
            await self._post_webhook(self.slack_webhook, slack_msg)

        # ── Discord (native embeds) ───────────────────────────────────────────
        if self.discord_webhook:
            # Helper: truncate to Discord limits and ensure never empty
            def dc(text, limit=1024):
                text = str(text or "N/A").strip() or "N/A"
                return text[:limit - 3] + "..." if len(text) > limit else text

            actions_text = "\n".join(
                f"{i+1}. {a}" for i, a in enumerate(triage_result.recommended_actions)
            ) or "See ticket"
            runbook_text = "\n".join(
                f"{i+1}. {s}" for i, s in enumerate(triage_result.runbook_steps)
            ) or "N/A"

            discord_payload = {
                "username": "ARIA – SRE Agent",
                "avatar_url": "https://cdn-icons-png.flaticon.com/512/2103/2103633.png",
                "embeds": [{
                    "title": dc(f"{emoji} {priority} Incident — {ticket.ticket_id}", 256),
                    "description": dc(triage_result.summary, 4096),
                    "color": DISCORD_COLORS.get(priority, 0x8B949E),
                    "fields": [
                        {
                            "name": "🔍 Root Cause",
                            "value": dc(triage_result.root_cause_hypothesis),
                            "inline": False,
                        },
                        {
                            "name": "⚙️ Affected Services",
                            "value": dc(services or "Unknown", 1024),
                            "inline": True,
                        },
                        {
                            "name": "📊 Confidence",
                            "value": dc(triage_result.confidence.title(), 256),
                            "inline": True,
                        },
                        {
                            "name": "💥 Blast Radius",
                            "value": dc(triage_result.estimated_blast_radius or "Under assessment"),
                            "inline": False,
                        },
                        {
                            "name": "🛠️ Recommended Actions",
                            "value": dc(actions_text),
                            "inline": False,
                        },
                        {
                            "name": "📋 Runbook",
                            "value": dc(runbook_text),
                            "inline": False,
                        },
                    ],
                    "footer": {
                        "text": f"ARIA  •  {ticket.provider.upper()} ticketing",
                    },
                    "url": ticket.url,
                }]
            }
            await self._post_discord(discord_payload)

        self.obs_logger.log_event("notify", "team_notified", {
            "ticket_id": ticket.ticket_id,
            "priority": priority,
            "channels": [
                "email",
                "slack" if self.slack_webhook else "",
                "discord" if self.discord_webhook else "",
            ],
        })

    # ── Reporter Confirmation ─────────────────────────────────────────────────
    async def notify_reporter(self, reporter_email: str, ticket, triage_result) -> None:
        priority = triage_result.priority
        emoji = PRIORITY_EMOJI.get(priority, "⚠️")
        subject = f"Your incident has been triaged – {ticket.ticket_id}"

        html_body = f"""
<html><body style="font-family: sans-serif; background: #f9f9f9; padding: 32px;">
<div style="max-width:580px; margin: auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,0.08);">
  <div style="background: #1a1a2e; padding: 24px 32px;">
    <h2 style="margin:0; color: #fff;">Your incident report has been received</h2>
  </div>
  <div style="padding: 32px;">
    <p>Hi,</p>
    <p>We've received your incident report and our SRE Agent has completed an initial triage. Here's what we found:</p>
    <table style="width:100%; border-collapse: collapse; margin: 16px 0;">
      <tr><td style="padding: 8px; color: #888; width: 40%;">Ticket ID</td><td style="padding: 8px; font-weight: bold;">{ticket.ticket_id}</td></tr>
      <tr style="background:#f8f8f8;"><td style="padding: 8px; color: #888;">Priority</td><td style="padding: 8px;">{emoji} {priority}</td></tr>
      <tr><td style="padding: 8px; color: #888;">Confidence</td><td style="padding: 8px;">{triage_result.confidence.title()}</td></tr>
    </table>
    <p><strong>Our engineering team has been notified</strong> and is reviewing the issue. You will receive another email when the incident is resolved.</p>
    <p style="color: #666; font-size: 14px;">If this is urgent, please also contact your account manager or our emergency line.</p>
    <a href="{ticket.url}" style="display: inline-block; margin-top: 16px; background: #1a1a2e; color: white; text-decoration: none; padding: 12px 24px; border-radius: 6px;">Track Ticket →</a>
  </div>
  <div style="padding: 16px 32px; background: #f0f0f0; color: #999; font-size: 12px;">
    SRE Agent – Automated Incident Management | Do not reply to this email
  </div>
</div>
</body></html>
"""
        await self._send_email(reporter_email, subject, html_body)
        self.obs_logger.log_event("notify", "reporter_confirmed", {
            "reporter": reporter_email,
            "ticket_id": ticket.ticket_id,
        })

    # ── Resolution Notification ───────────────────────────────────────────────
    async def notify_reporter_resolved(
        self,
        reporter_email: str,
        ticket_id: str,
        resolution_summary: str,
        resolved_by: str,
    ) -> None:
        subject = f"✅ Your incident has been resolved – {ticket_id}"
        html_body = f"""
<html><body style="font-family: sans-serif; background: #f9f9f9; padding: 32px;">
<div style="max-width:580px; margin: auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,0.08);">
  <div style="background: #0d7a5f; padding: 24px 32px;">
    <h2 style="margin:0; color: #fff;">✅ Incident Resolved – {ticket_id}</h2>
  </div>
  <div style="padding: 32px;">
    <p>Hi,</p>
    <p>We're happy to inform you that your incident has been resolved.</p>
    <p><strong>Resolution Summary:</strong><br>{resolution_summary}</p>
    <p><strong>Resolved by:</strong> {resolved_by}</p>
    <p>Thank you for your patience. If you experience further issues, please submit a new incident report.</p>
  </div>
  <div style="padding: 16px 32px; background: #f0f0f0; color: #999; font-size: 12px;">
    SRE Agent – Automated Incident Management
  </div>
</div>
</body></html>
"""
        await self._send_email(reporter_email, subject, html_body)

        # Discord resolution notice
        if self.discord_webhook:
            discord_payload = {
                "username": "SRE Agent",
                "avatar_url": "https://cdn-icons-png.flaticon.com/512/2103/2103633.png",
                "embeds": [{
                    "title": f"✅  Incident Resolved — {ticket_id}",
                    "description": resolution_summary,
                    "color": 0x3FB950,  # green
                    "fields": [
                        {
                            "name": "👤 Resolved by",
                            "value": resolved_by,
                            "inline": True,
                        },
                    ],
                    "footer": {"text": "SRE Agent  •  Incident closed"},
                }]
            }
            await self._post_discord(discord_payload)

        self.obs_logger.log_event("notify", "reporter_resolved", {
            "reporter": reporter_email,
            "ticket_id": ticket_id,
        })

    # ── Internal Helpers ──────────────────────────────────────────────────────
    async def _send_email(self, to: str, subject: str, html_body: str) -> None:
        if self.mock_email:
            logger.info(f"[MOCK EMAIL] To: {to} | Subject: {subject}")
            self.obs_logger.log_event("email", "mock_sent", {"to": to, "subject": subject})
            return
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.from_email
            msg["To"] = to
            msg.attach(MIMEText(html_body, "html"))
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as s:
                s.starttls()
                s.login(self.smtp_user, self.smtp_pass)
                s.sendmail(self.from_email, [to], msg.as_string())
            self.obs_logger.log_event("email", "sent", {"to": to, "subject": subject})
        except Exception as e:
            logger.error(f"Email send failed to {to}: {e}")
            self.obs_logger.log_event("email", "error", {"to": to, "error": str(e)})
            raise

    async def _post_webhook(self, url: str, payload: dict) -> None:
        """Generic webhook POST (used for Slack)."""
        try:
            async with httpx.AsyncClient() as client:
                r = await client.post(url, json=payload, timeout=10)
                r.raise_for_status()
            self.obs_logger.log_event("webhook", "sent", {"url": url[:60]})
        except Exception as e:
            logger.warning(f"Slack webhook failed: {e}")
            self.obs_logger.log_event("webhook", "error", {"error": str(e)})

    async def _post_discord(self, payload: dict) -> None:
        """Discord-native webhook POST (embeds format)."""
        try:
            async with httpx.AsyncClient() as client:
                r = await client.post(
                    self.discord_webhook,
                    json=payload,
                    timeout=10,
                )
                r.raise_for_status()
            self.obs_logger.log_event("discord", "sent", {"status": r.status_code})
            logger.info(f"Discord notification sent ✅ (status {r.status_code})")
        except Exception as e:
            logger.warning(f"Discord webhook failed: {e}")
            self.obs_logger.log_event("discord", "error", {"error": str(e)})